module.exports = {
    HK: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "HK",
        sys_region: "HK",
        carrier_region: "HK",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 45400
    },
    TW: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "TW",
        sys_region: "TW",
        carrier_region: "TW",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 46693
    },
    JP: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "JP",
        sys_region: "JP",
        carrier_region: "JP",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 46001
    },
    KR: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "KR",
        sys_region: "KR",
        carrier_region: "KR",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 450
    },
    US: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "US",
        sys_region: "US",
        carrier_region: "US",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 31001
    },
    SG: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "SG",
        sys_region: "SG",
        carrier_region: "SG",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 525
    },
    MY: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "MY",
        sys_region: "MY",
        carrier_region: "MY",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 502
    },
    AU: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "AU",
        sys_region: "AU",
        carrier_region: "AU",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 505
    },
    TH: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "TH",
        sys_region: "TH",
        carrier_region: "TH",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 520
    },
    KH: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "KH",
        sys_region: "KH",
        carrier_region: "KH",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 456
    },
    VN: {
        app_language: "vn",
        language: "vn",
        // timezone_name: "Asia/Shanghai",
        region: "VN",
        sys_region: "VN",
        carrier_region: "VN",
        account_region: "VN",
        carrier_region_v2: 452,
        is_my_cn: 0,
        mcc_mnc: 452
    },
    QA: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "QA",
        sys_region: "QA",
        carrier_region: "QA",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 427
    },
    AE: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "AE",
        sys_region: "AE",
        carrier_region: "AE",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 424
    },
    BN: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "BN",
        sys_region: "BN",
        carrier_region: "BN",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 505
    },
    LA: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "LA",
        sys_region: "LA",
        carrier_region: "LA",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 457
    },
    MN: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "MN",
        sys_region: "MN",
        carrier_region: "MN",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 428
    },
    PH: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "PH",
        sys_region: "PH",
        carrier_region: "PH",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 515
    },
    ID: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "ID",
        sys_region: "ID",
        carrier_region: "ID",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 510
    },
    BH: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "BH",
        sys_region: "BH",
        carrier_region: "BH",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 426
    },
    BT: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "BT",
        sys_region: "BT",
        carrier_region: "BT",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 402
    },
    KW: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "KW",
        sys_region: "KW",
        carrier_region: "KW",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 419
    },
    TD: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "TD",
        sys_region: "TD",
        carrier_region: "TD",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 622
    },
    TD: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "LC",
        sys_region: "LC",
        carrier_region: "LC",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 358
    },
    PG: {
        // app_language: "zh",
        // language: "zh",
        // timezone_name: "Asia/Shanghai",
        region: "PG",
        sys_region: "PG",
        carrier_region: "PG",
        // account_region: "MY",
        // carrier_region_v2: 46001,
        is_my_cn: 0,
        mcc_mnc: 537
    },
    CN: {
        app_language: "zh",
        region: "CN",
        language: "zh",
        timezone_name: "Asia/Shanghai",
        account_region: "CN",
        carrier_region: "CN",
        sys_region: "CN",
        carrier_region_v2: 46001,
        is_my_cn: 1,
        mcc_mnc: 460
    }
}